[window]
opacity = 0.95

[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black = '#665c54'
red = '#ea6962'
green = '#a9b665'
yellow = '#e78a4e'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#dfbf8e'

[colors.bright]
black = '#928374'
red = '#ea6962'
green = '#a9b665'
yellow = '#e3a84e'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#dfbf8e'

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[font]
size = 14
offset.y = 4

[terminal.shell]
program = "fish"

[mouse]
hide_when_typing = true

[terminal]
